import React from 'react';
import Head from 'next/head';
import { usePreviewControl } from '../hooks/usePreviewControl';

export type BaseLayoutProps = {

};

export function BaseLayout(props: React.PropsWithChildren<BaseLayoutProps>) {
    const theme = usePreviewControl({
        name: 'theme',
        type: 'enum',
        label: 'Theme',
        options: [
            { value: 'light', label: 'Light' },
            { value: 'dark', label: 'Dark' }
        ],
        required: true,
        value: typeof window === 'undefined' ? undefined : document.documentElement.classList.contains('dark') ? 'dark' : 'light',
        context: 'global'
    });

    React.useEffect(() => {
        const anyWindow = window as any;
        anyWindow.stackbitPreviewControls = [theme];
        return () => {
            anyWindow.stackbitPreviewControls = [];
        };
    });

    React.useEffect(() => {
        if (theme.value) {
            document.documentElement.classList.toggle('dark', theme.value === 'dark');
        }
    }, [theme]);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
            </Head>
            <main>{props.children}</main>
        </div>
    );
}
